### ISSUE TITLE
Add possibility to launch specific script

### ISSUE THREAD

**Issue by ghost** [gfi-centre-ouest/docker-devbox-ddb#2]
When you are updating, for example, a Dockerfile.mo file, in the current scripts you need to redo cd . in order to rebuild the final Dockerfile.

It would be great to have an optional parameter in ddb enter which will execute a part of the script such as :
```bash 
ddb enter --script=templates
```

**Comment by Toilal** [comment]
It should handle [glob](https://docs.python.org/fr/3.7/library/glob.html) patterns and multiple occurences.

**Comment by Toilal** [comment]
ddb now has a watch mode that supports automatic refresh of generated files when template changes. I also plan to make generated files read-only so that use won't be able to modify a generated file.
