### ISSUE TITLE
Make certresolver default value configurable

### ISSUE THREAD

**Issue by Toilal** [gfi-centre-ouest/docker-devbox-ddb#25]
certresolver can be configured inside libjsonnet VirtualHost function, but it would be easier to make the default value configurable with `traefik.certresolver` property. (currently, the default value is null).

**Comment by darkanakin41** [comment]
The configuration ```traefik.certresolver``` is not available in the jsonnet template if traefik feature is not enable and make the process crash. So I have moved it to ```docker.reverse_proxy.certresolver```.

It is in PR #38
