### ISSUE TITLE
Use .env files ??? 

### ISSUE THREAD

**Issue by darkanakin41** [gfi-centre-ouest/docker-devbox-ddb#3]
Maybe for environment variable, we should create ```.env``` like environment file that we create on folder entry, and then load it using bash : 

```bash
export $(grep -v '^#' .env | xargs)
```

Those .env file should be named using the terminal PID that we can retrieve using 
```bash 
echo $$
```

**Comment by Toilal** [comment]
There's no dependency on bash anymore.
