### ISSUE TITLE
Add custom router rule support for Traefik (HostRegexp, etc ...)

### ISSUE THREAD

**Issue by darkanakin41** [gfi-centre-ouest/docker-devbox-ddb#36]
https://docs.traefik.io/v2.0/routing/routers/#rule

**Comment by Toilal** [comment]
In jsonnet `TraefikLabels`, the hostname parameter is used for both local certificate generation (cfssl) and traefik router rule, so it's not that simple. 

I think we should add an additional and optional parameter to this function and `TraefikVirtualHost` function, named `router_rule` to override the default generated router rule from hostname (`"Host(`" + hostname + "`)"`).
