### ISSUE TITLE
Create a `ddb info` command

### ISSUE THREAD

**Issue by Toilal** [gfi-centre-ouest/docker-devbox-ddb#59]
It's sometime confusing to find out which URL to type in the browser to access the application, so `$(ddb activate)` should display a list of urls that can be accessed. This could be grabbed right from `docker-compose config` output.

Also, there should be a `ddb info` command that could display those urls.

**Comment by darkanakin41** [comment]
As discussed, `ddb activate` should keep only updating environment variable. 

Although, we will create the `ddb info` command which will display for each docker service :
* Virtual Host URL
* Exposed port
